# Generated by Django 4.2.1 on 2023-05-10 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_catpost_post_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catpost',
            name='name_cat',
            field=models.CharField(choices=[('health', 'Health'), ('meal', 'Meal'), ('exercise', 'Exercise')], max_length=20),
        ),
    ]
